---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobileservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobileservice-app
      version: v1.0.1
  template:
    metadata:
      name: mobileservice-pod
      labels:
        app: mobileservice-app
        version: v1.0.1
    spec:
      containers:
      - name: mobileservice-container
        image: hoangnguyenngoctb/mobileservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mobileservice-svc
  labels:
    app: mobileservice-app
spec:
  selector:
    app: mobileservice-app
    version: v1.0.1
  type: NodePort
  ports:
  - nodePort: 30500
    port: 5000
    targetPort: 5000