apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployapp
  template:
    metadata:
      name: podapp
      labels:
        app: deployapp
    spec:
      containers:
        - name: node
          image: ichte/swarmtest:node
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8085
